version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .build/docker/app.Dockerfile
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "8888:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    tty: true

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
